### ISSUE TITLE
Polyglot violates contributing.md

### ISSUE THREAD

**Issue by tzwel** [grantcarthew/awesome-unique-id#33]
I added this line
> If your submission is available in multiple programming languages, add as many implementations as possible to their respective categories.

to contributing.md in hopes to resolve any future situation like this, but it has occurred nonetheless lol. What do we do about this, do you think this rule is reasonable or do we remove it?

**Comment by grantcarthew** [comment]
It's just an interesting article I read this morning about UUIDv7. I initially put it under a subpoint of JS uuid, but thought better of it.

It doesn't make sense to add 22 language sections....  Not sure.

You decide @tzwel. It's a good repo though and should be somewhere.

**Comment by tzwel** [comment]
I don't know, honestly. Let's keep it like this until we come up with anything better
