### ISSUE TITLE
remove `shortid`?

### ISSUE THREAD

**Issue by adamfratino** [grantcarthew/awesome-unique-id#6]
Love the list! Just wanted to point out `shortid` is deprecated (see [npm page](https://www.npmjs.com/package/shortid)), and suggests `nanoid` as an alternative. Thought it might be a good idea to remove it from the list.

I can open a PR if you prefer, but didn't wanna go through the trouble if you don't think it should be removed.

**Comment by grantcarthew** [comment]
Fantastic feedback, thanks Adam.
I've switched out shortid for nanoid.
