### ISSUE TITLE
Any interest in adding human-id?

### ISSUE THREAD

**Issue by gradywetherbee** [grantcarthew/awesome-unique-id#7]
Seems like [human-id](https://github.com/RienNeVaPlus/human-id) might be a better solution at this point than [human-readable-ids](https://git.coolaj86.com/coolaj86/human-readable-ids.js.git).

Seems to be updated more recently and have a bigger pool size.

**Comment by grantcarthew** [comment]
Hi @gradywetherbee
Sorry, just seeing this now. Raise a PR and I'll merge.

**Comment by tzwel** [comment]
Added!
Would be cool if you explained why it's a better solution, then I might delete `human-readable-ids` completely.
@gradywetherbee

**Comment by tzwel** [comment]
Oops, I completely missed the explanation blatantly staring at me. Seems logical to remove, what do you think @grantcarthew ?

**Comment by grantcarthew** [comment]
It's supposed to be "Awesome" unique ids. human-id does seem better.

**Comment by tzwel** [comment]
Removed `human-readable-ids` in [9f16c3e](https://github.com/grantcarthew/awesome-unique-id/commit/9f16c3e1f4d279b0d768e77155e1205d8d56b59c)
